// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/mikeygenerator.png
var resourceMiKeyGeneratorPngData []byte
var resourceMiKeyGeneratorPng = &fyne.StaticResource{
	StaticName:    "icon/mikeygenerator.png",
	StaticContent: resourceMiKeyGeneratorPngData,
}
